version: "3"

services:
  dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    image: todo_app:dev
    volumes:
      - ./todo_app:/app/todo_app
    ports:
     - "5000:5000"
    env_file:
      - .env