- name: Run to do app
  hosts: servers
  remote_user: ec2-user

  tasks:
  - name: Install git and python3 if not installed
    ansible.builtin.yum:
      name:
        - git
        - python3
      state: present
    become: yes
  - name: Install poetry
    ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
    args:
      creates: ~/.local/bin/poetry
  - name: Create directory for to do app
    ansible.builtin.file:
      path: /opt/todoapp
      state: directory
      owner: ec2-user
    become: yes
  - name: Checkout git repo
    ansible.builtin.git:
      repo: 'https://github.com/danmousley367/DevOps-Course-Starter.git'
      dest: /opt/todoapp
      version: exercise-4
  - name: Install project dependencies
    ansible.builtin.command:
      chdir: /opt/todoapp
      cmd: /home/ec2-user/.local/bin/poetry install
  - name: Template a file to /etc/file.conf
    ansible.builtin.template:
      src: ./.env.j2
      dest: /opt/todoapp/.env
      owner: ec2-user
      mode: '0644'
  - name: Copy service file
    ansible.builtin.copy:
      src: ./todoapp.service
      dest: /etc/systemd/system/todoapp.service
      owner: ec2-user
      mode: '0644'
    become: yes
  - name: Start todoapp
    ansible.builtin.systemd_service:
      name: todoapp
      daemon_reload: true
      state: restarted
    become: yes

  vars_prompt:
  - name: trello_api_key
    prompt: Enter Trello API key 
    private: true
  - name: trello_api_token
    prompt: Enter Trello API token
    private: true
