name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
      - 'documentation/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'documentation/**'
  schedule:
    - cron: '0 5 * * mon'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build test image    
      run: docker build --target test -t todoapp:test .
    - name: Run unit and integration tests    
      run: docker run todoapp:test
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Slack Notification
      if: failure()
      uses: bryannice/gitactions-slack-notification@2.0.0
      env:
        SLACK_INCOMING_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        SLACK_MESSAGE: 'Pipeline ${{ github.run_number }} failed'
        SLACK_TITLE: 'To do app workflow'
        SLACK_CHANNEL: 'devops-pipeline'
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/exercise-9' }}
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: jpribyl/action-docker-layer-caching@v0.1.1
      continue-on-error: true
    - name: Build image
      run: docker build --target production --tag danmou367/my-todo-app:latest .
    - name: Publish image
      run: docker push danmou367/my-todo-app:latest
    - name: Allow Azure to pull latest image
      run: curl -dH --fail -X POST '${{ secrets.AZURE_WEBHOOK }}'
