name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo Hello World
    - name: Build test image    
      run: docker build --target test -t todoapp:test .