name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
      - 'documentation/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'documentation/**'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo Hello World
    - name: Build test image    
      run: docker build --target test -t todoapp:test .
    - name: Run unit and integration tests    
      run: docker run todoapp:test